# Generated by Django 5.1.5 on 2025-01-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_genre_start_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='start_page',
        ),
    ]
